# Generated by Django 6.0.2 on 2026-07-23 02:07

import app.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sala de chat',
                'verbose_name_plural': 'Salas de chat',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('grado_grupo', models.CharField(blank=True, max_length=50, verbose_name='Grado y grupo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('rol', models.CharField(choices=[('pasajero', 'Pasajero'), ('conductor', 'Conductor'), ('administrador', 'Administrador')], default='pasajero', max_length=20, verbose_name='Rol')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/perfiles/', verbose_name='Foto de perfil')),
                ('estado_cuenta', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('bloqueada', 'Bloqueada'), ('pendiente', 'Pendiente de verificación')], default='activa', max_length=20, verbose_name='Estado de la cuenta')),
                ('correo_verificado', models.BooleanField(default=False, verbose_name='Correo verificado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', app.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='InformacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.BooleanField(default=False, verbose_name='Tiene discapacidad')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo de sangre')),
                ('tipo_discapacidad', models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditiva', 'Auditiva'), ('motriz', 'Motriz'), ('intelectual', 'Intelectual'), ('psicosocial', 'Psicosocial'), ('multiple', 'Múltiple'), ('otra', 'Otra')], max_length=50, null=True, verbose_name='Tipo de discapacidad')),
                ('descripcion_discapacidad', models.TextField(blank=True, max_length=500, verbose_name='Descripción de discapacidad')),
                ('vehiculo_adaptado', models.BooleanField(default=False, verbose_name='Requiere vehículo adaptado')),
                ('cuidados_especiales', models.BooleanField(default=False, verbose_name='Requiere cuidados especiales')),
                ('usa_baston', models.BooleanField(default=False, verbose_name='Usa bastón')),
                ('usa_perro_guia', models.BooleanField(default=False, verbose_name='Usa perro guía')),
                ('usa_silla_ruedas', models.BooleanField(default=False, verbose_name='Usa silla de ruedas')),
                ('usa_andadera', models.BooleanField(default=False, verbose_name='Usa andadera')),
                ('usa_muletas', models.BooleanField(default=False, verbose_name='Usa muletas')),
                ('usa_protesis', models.BooleanField(default=False, verbose_name='Usa prótesis')),
                ('otro_apoyo', models.CharField(blank=True, max_length=150, verbose_name='Otro apoyo')),
                ('alergias', models.TextField(blank=True, max_length=500, verbose_name='Alergias')),
                ('medicamentos', models.TextField(blank=True, max_length=500, verbose_name='Medicamentos')),
                ('condiciones_medicas', models.TextField(blank=True, max_length=500, verbose_name='Condiciones médicas')),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto de emergencia')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de emergencia')),
                ('parentesco_contacto', models.CharField(blank=True, max_length=100, verbose_name='Parentesco')),
                ('observaciones', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('verificado', models.BooleanField(default=False, verbose_name='Información verificada')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_medica', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Información médica',
                'verbose_name_plural': 'Información médica',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=1000)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='app.salachat')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='LecturaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_leidos', to=settings.AUTH_USER_MODEL)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='app.mensaje')),
            ],
            options={
                'verbose_name': 'Lectura de mensaje',
                'verbose_name_plural': 'Lecturas de mensajes',
            },
        ),
        migrations.CreateModel(
            name='PerfilConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia', models.CharField(max_length=50, unique=True, verbose_name='Número de licencia')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('foto_licencia_frontal', models.ImageField(blank=True, null=True, upload_to='conductores/licencias/frontal/', verbose_name='Foto frontal de la licencia')),
                ('foto_licencia_reverso', models.ImageField(blank=True, null=True, upload_to='conductores/licencias/reverso/', verbose_name='Foto reverso de la licencia')),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20, verbose_name='Estado de verificación')),
                ('motivo_rechazo', models.TextField(blank=True, max_length=500, verbose_name='Motivo de rechazo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_conductor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de conductor',
                'verbose_name_plural': 'Perfiles de conductor',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueno', models.CharField(max_length=150, verbose_name='Dueño del vehículo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('placas', models.CharField(max_length=20, unique=True, verbose_name='Placas')),
                ('capacidad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Capacidad de pasajeros')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/fotos/', verbose_name='Foto del vehículo')),
                ('tarjeta_circulacion', models.ImageField(blank=True, null=True, upload_to='vehiculos/documentos/circulacion/', verbose_name='Tarjeta de circulación')),
                ('documento_seguro', models.ImageField(blank=True, null=True, upload_to='vehiculos/documentos/seguro/', verbose_name='Documento del seguro')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('inactivo', 'Inactivo')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('motivo_rechazo', models.TextField(blank=True, max_length=500, verbose_name='Motivo de rechazo')),
                ('activo', models.BooleanField(default=True, verbose_name='Vehículo activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='app.perfilconductor', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=255, verbose_name='Origen')),
                ('destino', models.CharField(max_length=255, verbose_name='Destino')),
                ('origen_latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('origen_longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('destino_latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('destino_longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fecha_hora_salida', models.DateTimeField(verbose_name='Fecha y hora de salida')),
                ('fecha_hora_llegada_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Llegada estimada')),
                ('asientos_totales', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Asientos ofrecidos')),
                ('asientos_disponibles', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Asientos disponibles')),
                ('costo_por_pasajero', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo por pasajero')),
                ('indicaciones', models.TextField(blank=True, max_length=500, verbose_name='Indicaciones')),
                ('permite_mascota', models.BooleanField(default=False)),
                ('acepta_silla_ruedas', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('disponible', 'Disponible'), ('completo', 'Sin lugares disponibles'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='disponible', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='app.perfilconductor', verbose_name='Conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='app.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['fecha_hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asientos_solicitados', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('punto_recogida', models.CharField(blank=True, max_length=255)),
                ('punto_descenso', models.CharField(blank=True, max_length=255)),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('requiere_asistencia', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_presentado', 'No se presentó')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_viaje', to=settings.AUTH_USER_MODEL)),
                ('respondida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app.viaje')),
            ],
            options={
                'verbose_name': 'Solicitud de viaje',
                'verbose_name_plural': 'Solicitudes de viaje',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddField(
            model_name='salachat',
            name='viaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sala_chat', to='app.viaje'),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('conducta', 'Conducta inapropiada'), ('acoso', 'Acoso'), ('seguridad', 'Problema de seguridad'), ('vehiculo', 'Problema con el vehículo'), ('incumplimiento', 'Incumplimiento'), ('fraude', 'Fraude'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(max_length=1000)),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='reportes/evidencias/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='pendiente', max_length=20)),
                ('respuesta_administrador', models.TextField(blank=True, max_length=1000)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_atendidos', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='app.viaje')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='ParadaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recogida', 'Punto de recogida'), ('intermedia', 'Parada intermedia'), ('descenso', 'Punto de descenso')], default='intermedia', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='app.viaje')),
            ],
            options={
                'verbose_name': 'Parada del viaje',
                'verbose_name_plural': 'Paradas del viaje',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud', 'Solicitud de viaje'), ('solicitud_aceptada', 'Solicitud aceptada'), ('solicitud_rechazada', 'Solicitud rechazada'), ('viaje', 'Información de viaje'), ('mensaje', 'Nuevo mensaje'), ('alerta', 'Alerta'), ('reporte', 'Reporte'), ('sistema', 'Sistema')], default='sistema', max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500)),
                ('url_destino', models.CharField(blank=True, max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_generadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app.solicitudviaje')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app.viaje')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GastoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gasolina', 'Gasolina'), ('estacionamiento', 'Estacionamiento'), ('caseta', 'Caseta'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], max_length=30)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='viajes/gastos/comprobantes/')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='app.perfilconductor')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='app.viaje')),
            ],
            options={
                'verbose_name': 'Gasto del viaje',
                'verbose_name_plural': 'Gastos de viajes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conductor', 'Calificación al conductor'), ('pasajero', 'Calificación al pasajero'), ('viaje', 'Calificación del viaje')], max_length=20)),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app.viaje')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('panico', 'Botón de pánico'), ('accidente', 'Accidente'), ('medica', 'Emergencia médica'), ('seguridad', 'Problema de seguridad'), ('otro', 'Otra emergencia')], default='panico', max_length=30)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('en_atencion', 'En atención'), ('resuelta', 'Resuelta'), ('falsa_alarma', 'Falsa alarma')], default='activa', max_length=20)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_emergencia', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_emergencia', to='app.viaje')),
            ],
            options={
                'verbose_name': 'Alerta de emergencia',
                'verbose_name_plural': 'Alertas de emergencia',
                'ordering': ['-fecha_activacion'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['matricula'], name='idx_usuario_matricula'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='idx_usuario_rol'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['estado_cuenta'], name='idx_usuario_estado'),
        ),
        migrations.AddConstraint(
            model_name='lecturamensaje',
            constraint=models.UniqueConstraint(fields=('mensaje', 'usuario'), name='lectura_unica_mensaje_usuario'),
        ),
        migrations.AddIndex(
            model_name='perfilconductor',
            index=models.Index(fields=['estado_verificacion'], name='idx_conductor_estado'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['sala', 'fecha_envio'], name='idx_mensaje_sala_fecha'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['placas'], name='idx_vehiculo_placas'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['estado'], name='idx_vehiculo_estado'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['estado', 'fecha_hora_salida'], name='idx_viaje_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['origen'], name='idx_viaje_origen'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['destino'], name='idx_viaje_destino'),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.CheckConstraint(condition=models.Q(('asientos_disponibles__lte', models.F('asientos_totales'))), name='viaje_disponibles_lte_totales'),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.CheckConstraint(condition=models.Q(('costo_por_pasajero__gte', 0)), name='viaje_costo_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='solicitudviaje',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='idx_solicitud_estado_fecha'),
        ),
        migrations.AddConstraint(
            model_name='solicitudviaje',
            constraint=models.UniqueConstraint(fields=('viaje', 'pasajero'), name='solicitud_unica_pasajero_viaje'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['estado', 'fecha_reporte'], name='idx_reporte_estado_fecha'),
        ),
        migrations.AddConstraint(
            model_name='reporte',
            constraint=models.CheckConstraint(condition=models.Q(('reportado_por', models.F('usuario_reportado')), _negated=True), name='reporte_no_autoreporte'),
        ),
        migrations.AddConstraint(
            model_name='paradaviaje',
            constraint=models.UniqueConstraint(fields=('viaje', 'orden'), name='parada_orden_unico_por_viaje'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='idx_notificacion_usuario_leida'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(fields=('viaje', 'autor', 'destinatario', 'tipo'), name='calificacion_unica_por_viaje'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.CheckConstraint(condition=models.Q(('autor', models.F('destinatario')), _negated=True), name='calificacion_no_autocalificacion'),
        ),
        migrations.AddIndex(
            model_name='alertaemergencia',
            index=models.Index(fields=['estado', 'fecha_activacion'], name='idx_alerta_estado_fecha'),
        ),
    ]
