# Generated by Django 6.0.7 on 2026-08-03 21:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_options_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='editada',
            field=models.BooleanField(default=False, verbose_name='Fue editada'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='estado',
            field=models.CharField(choices=[('visible', 'Visible'), ('reportada', 'Reportada'), ('en_revision', 'En revisión'), ('oculta', 'Oculta')], default='visible', max_length=20, verbose_name='Estado de moderación'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='motivo_moderacion',
            field=models.TextField(blank=True, max_length=500, verbose_name='Motivo de moderación'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisada por'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(blank=True, max_length=500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='puntuacion',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='tipo',
            field=models.CharField(choices=[('conductor', 'Calificación al conductor'), ('pasajero', 'Calificación al pasajero'), ('viaje', 'Calificación del viaje')], max_length=20, verbose_name='Tipo de calificación'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app.viaje', verbose_name='Viaje'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['tipo', 'puntuacion'], name='idx_calificacion_tipo_punt'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['estado', 'fecha'], name='idx_calificacion_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['destinatario', 'fecha'], name='idx_calificacion_dest_fecha'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.CheckConstraint(condition=models.Q(('puntuacion__gte', 1), ('puntuacion__lte', 5)), name='calificacion_puntuacion_valida'),
        ),
    ]
